import type { AuditLogEntry } from './types';

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: 'a1',
    action: 'Investigation created',
    actor: 'analyst.you',
    type: 'Create',
    severity: 'info',
    target: 'Investigation #204',
    occurredAt: '2026-07-20T09:12:00.000Z',
  },
  {
    id: 'a2',
    action: 'Note edited',
    actor: 'analyst.you',
    type: 'Update',
    severity: 'info',
    target: 'Investigation #204 — Notes',
    occurredAt: '2026-07-21T14:05:00.000Z',
  },
  {
    id: 'a3',
    action: 'Failed login attempt',
    actor: 'unknown',
    type: 'Login',
    severity: 'warning',
    target: 'Workspace session',
    occurredAt: '2026-07-21T22:47:00.000Z',
  },
  {
    id: 'a4',
    action: 'Evidence file deleted',
    actor: 'analyst.you',
    type: 'Delete',
    severity: 'critical',
    target: 'access_log_old.csv',
    occurredAt: '2026-07-22T08:03:00.000Z',
  },
  {
    id: 'a5',
    action: 'Plugin registered',
    actor: 'system',
    type: 'System',
    severity: 'info',
    target: 'reports plugin',
    occurredAt: '2026-07-22T08:00:00.000Z',
  },
  {
    id: 'a6',
    action: 'Local backup exported',
    actor: 'analyst.you',
    type: 'Export',
    severity: 'info',
    target: 'red_king_backup.json',
    occurredAt: '2026-07-24T18:45:00.000Z',
  },
  {
    id: 'a7',
    action: 'Investigation closed',
    actor: 'analyst.you',
    type: 'Update',
    severity: 'info',
    target: 'Investigation #204',
    occurredAt: '2026-07-22T16:30:00.000Z',
  },
  {
    id: 'a8',
    action: 'IOC entry deleted',
    actor: 'analyst.you',
    type: 'Delete',
    severity: 'warning',
    target: '192.0.2.44',
    occurredAt: '2026-07-24T11:20:00.000Z',
  },
];
