import type { OsintResult } from './types';

export const mockOsintResults: OsintResult[] = [
  {
    id: 'osint-1',
    query: '192.168.1.105',
    targetType: 'ip',
    source: 'GeoIP',
    title: 'GeoIP — 192.168.1.105',
    summary: 'Private RFC-1918 address, no geolocation available.',
    confidence: 'high',
    fetchedAt: '2026-07-20T09:00:00.000Z',
    data: {
      ip: '192.168.1.105',
      type: 'private',
      rfc: 'RFC-1918',
      range: '192.168.0.0/16',
      country: null,
      city: null,
      asn: null,
    },
  },
  {
    id: 'osint-2',
    query: '192.168.1.105',
    targetType: 'ip',
    source: 'Shodan',
    title: 'Shodan — 192.168.1.105',
    summary: 'Open ports: 22 (SSH), 80 (HTTP), 443 (HTTPS). Banner detected on port 80.',
    confidence: 'high',
    fetchedAt: '2026-07-20T09:01:00.000Z',
    data: {
      ip: '192.168.1.105',
      open_ports: [22, 80, 443],
      banners: {
        80: 'Apache/2.4.54 (Ubuntu)',
        443: 'nginx/1.22.0',
      },
      vulns: [],
      last_scan: '2026-07-19T18:00:00.000Z',
    },
  },
  {
    id: 'osint-3',
    query: 'lab.redking.local',
    targetType: 'domain',
    source: 'Whois',
    title: 'Whois — lab.redking.local',
    summary: 'Internal domain — no public WHOIS record found.',
    confidence: 'medium',
    fetchedAt: '2026-07-20T09:10:00.000Z',
    data: {
      domain: 'lab.redking.local',
      registrar: null,
      created: null,
      expires: null,
      nameservers: ['ns1.redking.local'],
      status: 'internal',
    },
  },
  {
    id: 'osint-4',
    query: 'lab.redking.local',
    targetType: 'domain',
    source: 'DNS',
    title: 'DNS — lab.redking.local',
    summary: 'A record resolves to 192.168.1.105. MX and TXT records also present.',
    confidence: 'high',
    fetchedAt: '2026-07-20T09:11:00.000Z',
    data: {
      domain: 'lab.redking.local',
      records: {
        A: ['192.168.1.105'],
        MX: ['mail.redking.local'],
        TXT: ['v=spf1 include:mail.redking.local ~all'],
        CNAME: [],
      },
      ttl: 300,
    },
  },
  {
    id: 'osint-5',
    query: 'lab.redking.local',
    targetType: 'domain',
    source: 'CertLog',
    title: 'CertLog — lab.redking.local',
    summary: '2 certificates found. Latest issued 2026-06-01, valid for 90 days.',
    confidence: 'high',
    fetchedAt: '2026-07-20T09:12:00.000Z',
    data: {
      domain: 'lab.redking.local',
      certificates: [
        {
          issuer: "Let's Encrypt",
          issued: '2026-06-01',
          expires: '2026-08-30',
          san: ['lab.redking.local', 'www.lab.redking.local'],
        },
        {
          issuer: 'Self-signed',
          issued: '2026-01-15',
          expires: '2027-01-15',
          san: ['lab.redking.local'],
        },
      ],
    },
  },
  {
    id: 'osint-6',
    query: 'analyst@redking.local',
    targetType: 'email',
    source: 'PasteBin',
    title: 'PasteBin — analyst@redking.local',
    summary: 'No pastes found referencing this address. Clean result.',
    confidence: 'high',
    fetchedAt: '2026-07-21T10:00:00.000Z',
    data: {
      email: 'analyst@redking.local',
      pastes_found: 0,
      last_checked: '2026-07-21T10:00:00.000Z',
    },
  },
  {
    id: 'osint-7',
    query: 'redking_operator',
    targetType: 'username',
    source: 'Social',
    title: 'Social — redking_operator',
    summary: 'Username found on 2 platforms (GitHub, HackerNews). No sensitive exposure.',
    confidence: 'medium',
    fetchedAt: '2026-07-21T10:30:00.000Z',
    data: {
      username: 'redking_operator',
      platforms: [
        { name: 'GitHub', url: 'https://github.com/redking_operator', public: true },
        { name: 'HackerNews', url: 'https://news.ycombinator.com/user?id=redking_operator', public: true },
      ],
      sensitive_exposure: false,
    },
  },
  {
    id: 'osint-8',
    query: '10.0.0.1',
    targetType: 'ip',
    source: 'GeoIP',
    title: 'GeoIP — 10.0.0.1',
    summary: 'Private address (RFC-1918). Commonly used as default gateway.',
    confidence: 'high',
    fetchedAt: '2026-07-22T08:00:00.000Z',
    data: {
      ip: '10.0.0.1',
      type: 'private',
      rfc: 'RFC-1918',
      range: '10.0.0.0/8',
      common_use: 'Default gateway',
    },
  },
  {
    id: 'osint-9',
    query: '10.0.0.1',
    targetType: 'ip',
    source: 'Shodan',
    title: 'Shodan — 10.0.0.1',
    summary: 'Open ports: 53 (DNS), 80 (HTTP), 8080 (HTTP-alt). Router admin panel on 8080.',
    confidence: 'medium',
    fetchedAt: '2026-07-22T08:01:00.000Z',
    data: {
      ip: '10.0.0.1',
      open_ports: [53, 80, 8080],
      banners: {
        8080: 'Router Admin Panel — Basic Auth',
      },
      vulns: ['CVE-2022-26919 (possible — unverified)'],
    },
  },
  {
    id: 'osint-10',
    query: 'a3f2c1b4d5e6f7a8b9c0d1e2f3a4b5c6',
    targetType: 'hash',
    source: 'Shodan',
    title: 'Shodan — Hash Lookup',
    summary: 'Hash not found in Shodan corpus. No associated services.',
    confidence: 'low',
    fetchedAt: '2026-07-22T09:00:00.000Z',
    data: {
      hash: 'a3f2c1b4d5e6f7a8b9c0d1e2f3a4b5c6',
      found: false,
      type: 'MD5 (inferred)',
    },
  },
];
